dist: trusty
sudo: required
language: python
python:
- "3.6"
install: "pip install -r requirements.txt"
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.6"
script:
  - python manage.py test
